<?php namespace RainLab\Pages\Components;

use Cms\Classes\ComponentBase;
use Cms\Classes\Theme;
use RainLab\Pages\Classes\Menu as PagesMenu;

/**
 * StaticMenu component outputs a menu in a CMS layout.
 */
class StaticMenu extends ComponentBase
{
    /**
     * @var string menuName of the menu
     */
    public $menuName;

    /**
     * @var array menuItems generated by the menu, each a RainLab\Pages\Classes\MenuItemReference object
     */
    protected $menuItems;

    /**
     * componentDetails
     */
    public function componentDetails()
    {
        return [
            'name'        => 'Static menu',
            'description' => 'Outputs a menu in a CMS layout.'
        ];
    }

    /**
     * defineProperties
     */
    public function defineProperties()
    {
        return [
            'code' => [
                'title'       => 'Menu',
                'description' => 'Specify a code of the menu the component should output.',
                'type'        => 'dropdown'
            ]
        ];
    }

    /**
     * getCodeOptions
     */
    public function getCodeOptions()
    {
        $result = [];

        $theme = Theme::getEditTheme();
        $menus = PagesMenu::listInTheme($theme, true);

        foreach ($menus as $menu) {
            $result[$menu->code] = $menu->name;
        }

        return $result;
    }

    /**
     * onRun
     */
    public function onRun()
    {
        $this->page['menuItems'] = $this->menuItems();
    }

    /**
     * menuItems
     */
    public function menuItems()
    {
        if ($this->menuItems !== null) {
            return $this->menuItems;
        }

        if (!strlen($this->property('code'))) {
            return;
        }

        $theme = Theme::getActiveTheme();
        $menu = PagesMenu::loadCached($theme, $this->property('code'));

        if ($menu) {
            $this->menuItems = $menu->generateReferences($this->page);
            $this->menuName = $menu->name;
        }

        return $this->menuItems;
    }

    /**
     * totalItems counts the total menu items, including children
     */
    public function totalItems()
    {
        $countAll = function($items) use (&$countAll) {
            $count = count($items);

            foreach ($items as $item) {
                if (!isset($item->items)) {
                    continue;
                }

                $count += $countAll($item->items);
            }

            return $count;
        };

        return $countAll($this->menuItems());
    }

    /**
     * resetMenu resets the menu code and rebuilds the menu
     */
    public function resetMenu($code)
    {
        $this->setProperty('code', $code);
        $this->menuItems = null;

        return $this->page['menuItems'] = $this->menuItems();
    }
}
